### ISSUE TITLE
Resource owner id is not correct

### ISSUE THREAD

**Issue by shadowhand** [thephpleague/oauth2-github#1]
The [getId](https://github.com/thephpleague/oauth2-github/blob/5f48034ee21bb025b4710f9e2e587a9a094bc9ff/src/Provider/GithubResourceOwner.php#L53) method should be returning the actual value, not the key name.

**Comment by shadowhand** [comment]
Also, I would not recommend extending `GenericResourceOwner` for `GithubResourceOwner` as it doesn't offer much of value.

**Comment by stevenmaguire** [comment]
I've addressed these concerns. I did not find the name `resourceOwnerId` within the generic class to be intuitive. It no longer matters, this resource owner is no longer extending that class and has implemented the expected behavior correctly now.
