### ISSUE TITLE
Bad PhpDocs

### ISSUE THREAD

**Issue by dac514** [thephpleague/oauth2-github#11]
Stuff like this makes it very hard to navigate the code base when debugging...

![bad-phpdocs-2](https://user-images.githubusercontent.com/812192/30218119-2d700cfc-9486-11e7-823a-bd4ccbf503b4.PNG)

My IDE thinks $data is a string because the project says so.

![bad-phpdocs](https://user-images.githubusercontent.com/812192/30218125-31b99fda-9486-11e7-9c5a-2854475596b7.PNG)

My IDE doesn't recognize the namespaces (first slash is missing, so it's relative), $data is declared a string, throws is not right.

I use PhpStorm.

Thank you for your consideration.

**Comment by shadowhand** [comment]
Valid points. The documentation is a hold over from pre-2.0 when `$data` wasn't parsed at this point. I will update.
