### ISSUE TITLE
Type error in GithubResourceOwner 

### ISSUE THREAD

**Issue by Seldaek** [thephpleague/oauth2-github#17]
This here declares string|null 

https://github.com/thephpleague/oauth2-github/blob/master/src/Provider/GithubResourceOwner.php#L38

But calling it returns an int. I'm not sure if the docblock should be fixed or if it should be cast to a string.. But I guess fixing the docblock is the most BC change.

**Comment by shadowhand** [comment]
Released in version 3.0.0
