### ISSUE TITLE
Refreshing token,

### ISSUE THREAD

**Issue by craftpip** [thephpleague/oauth2-github#2]
```
$token = $provider->getAccessToken('authorization_code', [
    'code' => $_GET['code']
]);
```

The token returned does not contain refresh token & expire, 
How do i refresh tokens ?

Thank you,

**Comment by stevenmaguire** [comment]
Github does not support refresh tokens. From what I have read they also do not "expire" and are assumed to be for "offline use". Therefore the user would have to revoke the token. 

In any case, if you needed a new access token, you would need to send the user through the complete OAuth flow again.

You can read more in [the official docs](https://developer.github.com/v3/oauth/) and [a popular guide](https://gist.github.com/technoweenie/419219).

**Comment by craftpip** [comment]
Thank you for the support @stevenmaguire
