### ISSUE TITLE
Link header

### ISSUE THREAD

**Issue by pdewouters** [thephpleague/oauth2-github#6]
How do I get the Link header for pagination? I tried `$provider->getHeaders()` that returns nothing

**Comment by shadowhand** [comment]
You will need to get it from the response of an API request using [PSR-7 methods](http://www.php-fig.org/psr/psr-7/):

``` php
$request = $provider->getAuthenticatedRequest(...);
$response = $provider->getHttpClient()->send($request);
$link = $response->getHeader('Link');
```

**Comment by pdewouters** [comment]
So there's no methods to help with pagination in the library?

**Comment by shadowhand** [comment]
This package is only an OAuth2 provider. It can be used as an API helper but doesn't provide any methods to support that.
