### ISSUE TITLE
composer error on installing

### ISSUE THREAD

**Issue by afzaalhussain50** [thephpleague/oauth2-github#7]
i am facing this problem, why its give me this error ? kindly help me..!!
Thanks

![capture](https://cloud.githubusercontent.com/assets/11573574/17648034/901317ca-6221-11e6-8040-1b48d38d0be0.PNG)

**Comment by shadowhand** [comment]
You're adding `$` to the installation command, which is not necessary. It is included in the README to indicate a console command.

**Comment by ramsey** [comment]
Can you show the contents of your `composer.json` file? Aside from the misuse of `$` the first time you run the commands, when you do run the command correctly, you're getting an error about Composer being unable to satisfy requirements. This could be due to any number of issues, and seeing the contents of your  `composer.json` will help us troubleshoot.

Thanks!

**Comment by afzaalhussain50** [comment]
Thank you all of you for giving me your time, this is my composer.json file contents...!!

{
    "name": "league/oauth2-github",
    "description": "Github OAuth 2.0 Client Provider for The PHP League OAuth2-Client",
    "license": "MIT",
    "authors": [
        {
            "name": "Steven Maguire",
            "email": "stevenmaguire@gmail.com",
            "homepage": "https://github.com/stevenmaguire"
        }
    ],
    "keywords": [
        "oauth",
        "oauth2",
        "client",
        "authorization",
        "authorisation",
        "github"
    ],
    "require": {
        "php": ">=5.5.0",
        "league/oauth2-client": "~1.0"
    },
    "require-dev": {
        "phpunit/phpunit": "~4.0",
        "mockery/mockery": "~0.9",
        "squizlabs/php_codesniffer": "~2.0"
    },
    "autoload": {
        "psr-4": {
            "League\OAuth2\Client\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "League\OAuth2\Client\Test\": "test/src/"
        }
    },
    "extra": {
        "branch-alias": {
            "dev-master": "1.0.x-dev"
        }
    }
}

**Comment by ramsey** [comment]
This is the `composer.json` file for the league/oauth2-github package. Do you have a `composer.json` file for your own project?

**Comment by afzaalhussain50** [comment]
no, i want to install this package but its give me error, i already installed oauth2-google package its successfully installed but this one give me error.

**Comment by ramsey** [comment]
I recommend reading this guide to Composer first. Let me know if you still have installation issues afterwards.

https://scotch.io/tutorials/a-beginners-guide-to-composer

**Comment by afzaalhussain50** [comment]
ok thanks :)
